### ISSUE TITLE
svelte-kit-connect-cloudflare-kv breaks SessionData typing

### ISSUE THREAD

**Issue by HIBIKI-CUBE** [yutak23/svelte-kit-connect-cloudflare-kv#1]
(本文は日本語で失礼します)

`svelte-kit-sessions`と`svelte-kit-connect-cloudflare-kv`をいっしょに使う際に、SessionDataへの型付けがうまく機能しなくなります。

たとえば`src/hooks.server.ts`の中で以下のように記述しているとします。
```ts
declare module 'svelte-kit-sessions' {
  interface SessionData {
    userId?: string;
    challenge?: string;
  }
}
```
これにより`+server.ts`などの中では`event.locals.session.data`の中に`userId`と`challenge`の型がそれぞれ認識されます。

この状態で`svelte-kit-connect-cloudflare-kv`を`import`すると、この型付けが効かなくなります。
(`SessionData`の中身が`{}`と認識されてしまう)

一旦のワークアラウンドとして`src/hooks.server.ts`に以下の記述を追加しています。
```ts
import type { SessionData as OriginalSessionData } from 'svelte-kit-sessions';

declare module 'svelte-kit-connect-cloudflare-kv' {
  interface SessionData extends OriginalSessionData{}
}
```

この対応で型は元通り正しく機能するようになります。

**Comment by yutak23** [comment]
ライブラリの利用ありがとうございます。
そして対応が遅れてすみません。
型引数で解消されそうでしたので、型引数を設定できるように改修しました。
